// Admin Catalog -- approval queue, proposals, discounts, ingest, mappings, verifiers, specs
// v0.1 | 2026-05-15 | Job_PM [V8 SHADOW]

import type { Proposal, DiscountRule, IngestStaging, SkuMapping, VerifierStatus, SpecializationProposal } from './catalogMock';

// ============================================================================
// APPROVAL QUEUE -- proposals awaiting Facu
// ============================================================================

export const PROPOSALS: Proposal[] = [
  {
    id: 'prop_001',
    type: 'shipping_config',
    scope: 'BOG -> US-WEST (AndesColor CO)',
    current_value: 'no config (CO disabled)',
    proposed_value: '$7.20/kg base + 1.30 fuel mult + dim_div 6000 + REL-CO-44567',
    proposed_by: 'Job_PM',
    proposed_at: '2026-05-14',
    status: 'awaiting_facu',
    warnings: [
      { severity: 'warn', text: 'No FedEx label confirmation yet -- rates self-reported by AndesColor' },
      { severity: 'info',  text: 'Approving unlocks 5 hidden SKUs (3 live + 2 draft)' },
    ],
    cascade_impact_skus: 5,
    cascade_top_examples: [
      { sku: 'Hortensia Azul Premium (AndesColor)', before: 'hidden (no shipping)', after: 'live @ ~$3.60/stem' },
      { sku: 'Hortensia Blanca Jumbo (AndesColor)', before: 'hidden (no shipping)', after: 'live @ ~$3.45/stem' },
      { sku: 'Rosa Mondial 60 (CO)',                 before: 'hidden (no shipping)', after: 'live @ ~$1.30/stem' },
    ],
  },
  {
    id: 'prop_002',
    type: 'shipping_config',
    scope: 'AMS -> US-EAST (DutchFlora NL)',
    current_value: 'no config (NL disabled)',
    proposed_value: '$9.50/kg base + 1.15 fuel mult + dim_div 6000 + $12/box customs + REL-NL-pending',
    proposed_by: 'Job_PM',
    proposed_at: '2026-05-14',
    status: 'awaiting_facu',
    warnings: [
      { severity: 'critical', text: 'REL_NUMBER not assigned by FedEx yet -- placeholder' },
      { severity: 'warn',     text: 'Customs fee guess $12/box; needs broker confirm' },
      { severity: 'info',     text: 'Approving unlocks 4 hidden SKUs (2 live + 2 draft)' },
    ],
    cascade_impact_skus: 4,
    cascade_top_examples: [
      { sku: 'Peony Sarah Bernhardt 50cm (NL)', before: 'hidden', after: 'live @ ~$3.95/stem' },
      { sku: 'Peony Coral Charm 50cm (NL)',     before: 'hidden', after: 'live @ ~$4.40/stem' },
    ],
  },
  {
    id: 'prop_003',
    type: 'gpm_target',
    scope: 'Category: rose (premium varieties)',
    current_value: 'GPM target 33%',
    proposed_value: 'GPM target 35% for varieties: Antonia, Quicksand, H&F Magic',
    proposed_by: 'Job_PM',
    proposed_at: '2026-05-13',
    status: 'awaiting_facu',
    warnings: [
      { severity: 'warn', text: '7 SKUs drop below GPM floor (28%) if competitors hold their price' },
      { severity: 'info', text: 'Projected revenue uplift: +$420/wk @ current volume' },
    ],
    cascade_impact_skus: 7,
    cascade_top_examples: [
      { sku: 'Rose Antonia Garden 60cm (Ecoroses)', before: '$1.72/stem', after: '$1.82/stem' },
      { sku: 'Rose H&F Magic 60cm (Ecoroses)',      before: '$1.38/stem', after: '$1.45/stem' },
      { sku: 'Rose Quicksand 60cm (Ecoroses)',      before: '$1.87/stem (hidden)', after: '$1.98/stem (hidden)' },
    ],
  },
  {
    id: 'prop_004',
    type: 'discount',
    scope: 'Client: Buonasera Events',
    current_value: 'no client discount',
    proposed_value: '15% off all roses, expires 2026-08-31',
    proposed_by: 'Talin',
    proposed_at: '2026-05-13',
    status: 'awaiting_facu',
    warnings: [
      { severity: 'warn', text: 'Margin on Freedom Red 60cm drops from 33% -> 19.5% (below GPM floor 28%)' },
      { severity: 'info', text: 'Buonasera 12-mo revenue: $24k, AOV $1,850, retention 8/9 months' },
    ],
    cascade_impact_skus: 11,
    cascade_top_examples: [
      { sku: 'Rose Freedom Red 60cm (Ecoroses)', before: '$1.14/stem', after: '$0.97/stem (GPM 19.5%)' },
      { sku: 'Rose Mondial 60cm (Ecoroses)',     before: '$1.17/stem', after: '$0.99/stem (GPM 20.1%)' },
    ],
  },
  {
    id: 'prop_005',
    type: 'visibility',
    scope: 'T3 stock=0 SKUs',
    current_value: 'auto-hidden if stems=0',
    proposed_value: 'show on website with "Request quote -- 14d delivery" badge',
    proposed_by: 'Job_PM',
    proposed_at: '2026-05-12',
    status: 'awaiting_facu',
    warnings: [
      { severity: 'warn', text: '87 SKUs become visible -- risk of customer expectation mismatch on delivery' },
      { severity: 'info', text: 'Lift to /quote conversion estimated at +0.15 pp; mitigates 41% L7 traffic drop' },
    ],
    cascade_impact_skus: 87,
    cascade_top_examples: [
      { sku: 'Rose Quicksand 60cm (Ecoroses T3)', before: 'hidden', after: 'visible w/ 14d badge' },
      { sku: 'Hydrangea White Jumbo (MF T3)',     before: 'hidden', after: 'visible w/ 14d badge' },
    ],
  },
  {
    id: 'prop_006',
    type: 'box_dim',
    scope: 'Magic Flowers QB-MF box code',
    current_value: 'QB-MF (provisional code, dims verified)',
    proposed_value: 'confirm Komet code w/ Magic Flowers, lock in DB',
    proposed_by: 'Rose',
    proposed_at: '2026-05-12',
    status: 'awaiting_facu',
    warnings: [
      { severity: 'info', text: 'Box dims FedEx-verified (4 labels Mar 19). Code only is provisional.' },
    ],
    cascade_impact_skus: 6,
    cascade_top_examples: [
      { sku: 'High & Flame Magic 60cm (MF)', before: 'price unchanged', after: 'price unchanged + code locked' },
    ],
  },
  {
    id: 'prop_007',
    type: 'shipping_config',
    scope: 'EC -> US-WEST -- FedEx fuel surcharge',
    current_value: 'fuel mult 1.25',
    proposed_value: 'fuel mult 1.30 (FedEx notice 2026-05-10)',
    proposed_by: 'Job_PM',
    proposed_at: '2026-05-12',
    status: 'awaiting_facu',
    warnings: [
      { severity: 'critical', text: '213 SKUs affected. Delivery cost rises ~4% per stem. Floropolis price rises ~1.2%.' },
      { severity: 'warn',     text: '5 SKUs drop below GPM floor 28% if fuel passed through fully' },
    ],
    cascade_impact_skus: 213,
    cascade_top_examples: [
      { sku: 'Rose Mondial 60cm (Ecoroses)', before: '$1.17/stem', after: '$1.18/stem' },
      { sku: 'Rose Freedom Red 60cm (Ecoroses)', before: '$1.14/stem', after: '$1.15/stem' },
    ],
  },
  {
    id: 'prop_008',
    type: 'discount',
    scope: 'Category: delphinium',
    current_value: 'no category discount',
    proposed_value: '20% off all delphinium for Q3 2026',
    proposed_by: 'Talin',
    proposed_at: '2026-05-11',
    status: 'awaiting_facu',
    warnings: [
      { severity: 'warn', text: 'Margin on Sea Waltz drops 33% -> 16.6%. Below GPM floor.' },
      { severity: 'info', text: 'Inventory surplus risk -- Flodecol over-supplying Sea Waltz since Apr' },
    ],
    cascade_impact_skus: 2,
    cascade_top_examples: [
      { sku: 'Delphinium Sea Waltz 80cm (Flodecol)', before: '$1.61/stem', after: '$1.29/stem (GPM 16.6%)' },
    ],
  },
];

// ============================================================================
// DISCOUNT RULES -- existing + proposed
// ============================================================================

export const DISCOUNT_RULES: DiscountRule[] = [
  {
    id: 'disc_001',
    scope_type: 'client',
    scope_value: 'client_selena_ross',
    scope_label: 'Selena Ross Flowers',
    discount_pct: 8,
    expires_at: '2026-12-31',
    warnings: [],
    status: 'active',
    approved_by: 'Facu',
    approved_at: '2026-02-15',
    notes: 'Long-term client (3+ years), volume >$2k/month',
  },
  {
    id: 'disc_002',
    scope_type: 'category',
    scope_value: 'hydrangea',
    scope_label: 'All hydrangea',
    discount_pct: 5,
    expires_at: '2026-06-30',
    warnings: [{ severity: 'info', text: 'Seasonal: spring surplus from Magic Flowers' }],
    status: 'active',
    approved_by: 'Facu',
    approved_at: '2026-04-01',
  },
  {
    id: 'disc_003',
    scope_type: 'sku',
    scope_value: 'sku_eco_rainbow_50',
    scope_label: 'Rose Rainbow 50cm (Ecoroses)',
    discount_pct: 12,
    expires_at: '2026-05-31',
    warnings: [{ severity: 'warn', text: 'Margin drops 33% -> 22.7% on this SKU' }],
    status: 'active',
    approved_by: 'Facu',
    approved_at: '2026-05-05',
    notes: 'Move-volume play, vendor over-supplied',
  },
  // Proposed (awaiting_facu) duplicates of approval queue items for consistency
  {
    id: 'disc_004',
    scope_type: 'client',
    scope_value: 'client_buonasera',
    scope_label: 'Buonasera Events',
    discount_pct: 15,
    expires_at: '2026-08-31',
    warnings: [{ severity: 'warn', text: 'Margin on Freedom Red 60cm drops 33% -> 19.5% (below floor 28%)' }],
    status: 'awaiting_facu',
    notes: 'Talin proposal -- retention reward, 12mo revenue $24k',
  },
  {
    id: 'disc_005',
    scope_type: 'category',
    scope_value: 'delphinium',
    scope_label: 'All delphinium',
    discount_pct: 20,
    expires_at: '2026-09-30',
    warnings: [{ severity: 'warn', text: 'Sea Waltz margin drops 33% -> 16.6%. Below GPM floor.' }],
    status: 'awaiting_facu',
    notes: 'Q3 inventory clearance -- Flodecol over-supplying',
  },
  {
    id: 'disc_006',
    scope_type: 'vendor',
    scope_value: 'v_dutchflora',
    scope_label: 'DutchFlora NL (intro offer)',
    discount_pct: 10,
    expires_at: '2026-07-31',
    warnings: [{ severity: 'info', text: 'Onboarding incentive. Vendor reliability score 45/100.' }],
    status: 'awaiting_facu',
    notes: 'Onboarding offer to drive trial volume',
  },
];

// ============================================================================
// INGEST STAGING -- vendor uploads pending review
// ============================================================================

export const INGEST_STAGING: IngestStaging[] = [
  {
    id: 'ing_001',
    vendor_id: 'v_ecoroses',
    received_at: '2026-05-15T05:02:00Z',
    source: 'api',
    raw_input_preview: 'K2K eShop v3 sync -- 47 SKUs (43 unchanged, 4 cost updated, 0 new)',
    parsed_offers: 47,
    mapping_confidence_avg: 0.99,
    status: 'auto_applied',
    mapped_sku_count: 47,
    unmapped_count: 0,
    parser_agent: 'Vendor Ingestion Adapter',
  },
  {
    id: 'ing_002',
    vendor_id: 'v_magicflowers',
    received_at: '2026-05-15T05:14:00Z',
    source: 'api',
    raw_input_preview: 'K2K eShop v3 sync -- 28 SKUs (25 unchanged, 1 cost updated, 2 new from Viviana)',
    parsed_offers: 28,
    mapping_confidence_avg: 0.94,
    status: 'partial_mapped',
    mapped_sku_count: 26,
    unmapped_count: 2,
    parser_agent: 'Vendor Ingestion Adapter',
  },
  {
    id: 'ing_003',
    vendor_id: 'v_andescolor',
    received_at: '2026-05-15T09:32:00Z',
    source: 'whatsapp',
    raw_input_preview: 'Voice note (47s) + 6 photos from Carlos M. "Buen dia Facu, esta semana tengo hortensia azul jumbo 240 tallos a $1.95, blanca 120 tallos a $1.85..."',
    parsed_offers: 6,
    mapping_confidence_avg: 0.71,
    status: 'pending_review',
    mapped_sku_count: 4,
    unmapped_count: 2,
    parser_agent: 'Vendor Ingestion Adapter',
  },
  {
    id: 'ing_004',
    vendor_id: 'v_dutchflora',
    received_at: '2026-05-14T11:08:00Z',
    source: 'email',
    raw_input_preview: 'Weekly avail PDF (4pp) + inline list. "Dear partner, our offer for week 21..."',
    parsed_offers: 12,
    mapping_confidence_avg: 0.63,
    status: 'pending_review',
    mapped_sku_count: 7,
    unmapped_count: 5,
    parser_agent: 'Vendor Ingestion Adapter',
  },
  {
    id: 'ing_005',
    vendor_id: 'v_flodecol',
    received_at: '2026-05-15T05:18:00Z',
    source: 'api',
    raw_input_preview: 'K2K eShop v3 sync -- 22 SKUs (all unchanged)',
    parsed_offers: 22,
    mapping_confidence_avg: 0.98,
    status: 'auto_applied',
    mapped_sku_count: 22,
    unmapped_count: 0,
    parser_agent: 'Vendor Ingestion Adapter',
  },
  {
    id: 'ing_006',
    vendor_id: 'v_andescolor',
    received_at: '2026-05-13T16:21:00Z',
    source: 'whatsapp',
    raw_input_preview: 'Photo: handwritten note of rose varieties + price list',
    parsed_offers: 8,
    mapping_confidence_avg: 0.45,
    status: 'rejected',
    mapped_sku_count: 0,
    unmapped_count: 8,
    parser_agent: 'Vendor Ingestion Adapter',
  },
];

// ============================================================================
// SKU MAPPING QUEUE -- low-confidence matches awaiting human review
// ============================================================================

export const SKU_MAPPINGS: SkuMapping[] = [
  {
    id: 'map_001',
    vendor_id: 'v_andescolor',
    raw_name: 'Rosa Aqua-Blue',
    raw_attributes: [
      { key: 'length',  value: '60cm' },
      { key: 'box',     value: 'QB' },
      { key: 'color',   value: 'Blue/Aqua' },
    ],
    suggested_quality_family_id: 'qf_rose_coolwater_60',
    suggested_quality_family_name: 'Rose Cool Water 60cm',
    confidence: 0.72,
    alternatives: [
      { quality_family_id: 'qf_rose_mondial_60', quality_family_name: 'Rose Mondial 60cm', confidence: 0.41 },
      { quality_family_id: '', quality_family_name: '+ Create new quality family', confidence: 0 },
    ],
    status: 'pending',
  },
  {
    id: 'map_002',
    vendor_id: 'v_dutchflora',
    raw_name: 'Ranonkel Amandine Mix',
    raw_attributes: [
      { key: 'length', value: '40cm' },
      { key: 'box',    value: 'EB-NL' },
      { key: 'colors', value: 'mixed' },
    ],
    suggested_quality_family_id: 'qf_ranunculus_amandine',
    suggested_quality_family_name: 'Ranunculus Amandine Assorted',
    confidence: 0.81,
    alternatives: [
      { quality_family_id: '', quality_family_name: '+ Create new quality family', confidence: 0 },
    ],
    status: 'pending',
  },
  {
    id: 'map_003',
    vendor_id: 'v_dutchflora',
    raw_name: 'Anemone Mariane Bordeaux',
    raw_attributes: [
      { key: 'length', value: '35-40cm' },
      { key: 'color',  value: 'Bordeaux/Burgundy' },
    ],
    suggested_quality_family_id: 'qf_anemone_mariane_burgundy',
    suggested_quality_family_name: 'Anemone Burgundy Mariane 35cm',
    confidence: 0.78,
    alternatives: [
      { quality_family_id: 'qf_anemone_mariane_fuchsia', quality_family_name: 'Anemone Fuchsia Mariane 35-40cm', confidence: 0.32 },
    ],
    status: 'pending',
  },
  {
    id: 'map_004',
    vendor_id: 'v_andescolor',
    raw_name: 'Ranunculo Amandine Surtido',
    raw_attributes: [
      { key: 'length', value: '40cm' },
      { key: 'colors', value: 'assorted' },
    ],
    suggested_quality_family_id: 'qf_ranunculus_amandine',
    suggested_quality_family_name: 'Ranunculus Amandine Assorted',
    confidence: 0.84,
    alternatives: [],
    status: 'pending',
  },
  {
    id: 'map_005',
    vendor_id: 'v_dutchflora',
    raw_name: 'Tulpen Strong Gold 50cm',
    raw_attributes: [
      { key: 'length', value: '50cm' },
      { key: 'box',    value: 'EB-NL' },
    ],
    suggested_quality_family_id: '',
    suggested_quality_family_name: '(no match -- unknown variety)',
    confidence: 0.18,
    alternatives: [
      { quality_family_id: '', quality_family_name: '+ Create new quality family "Tulip Strong Gold 50cm"', confidence: 0 },
    ],
    status: 'pending',
  },
  {
    id: 'map_006',
    vendor_id: 'v_andescolor',
    raw_name: 'Hortensia Azul Jumbo',
    raw_attributes: [
      { key: 'length', value: '70cm' },
      { key: 'box',    value: 'QB-CO' },
    ],
    suggested_quality_family_id: 'qf_hydrangea_blue',
    suggested_quality_family_name: 'Hydrangea Blue Premium',
    confidence: 0.91,
    alternatives: [],
    status: 'accepted',
  },
];

// ============================================================================
// VERIFIER STATUS -- Pipeline Law (one per layer)
// ============================================================================

export const VERIFIER_STATUSES: VerifierStatus[] = [
  { layer: '0 -- Vendors',           verifier_name: 'verify_vendors.py',          status: 'MISSING', last_run_at: '',                       message: 'DDL not built. No verifier exists.' },
  { layer: '1 -- SKU Master',        verifier_name: 'verify_sku_master.py',       status: 'WARN',    last_run_at: '2026-05-15 05:03 PDT',   message: 'Ecoroses only -- MF/Flodecol/Megaflor/Olimpo not generalized' },
  { layer: '2 -- Cost',              verifier_name: 'verify_costs.py',            status: 'WARN',    last_run_at: '2026-05-15 05:05 PDT',   message: 'MF: 90 verified + 10 awaiting Viviana. Megaflor: 0 costs.' },
  { layer: '3 -- Boxes + Shipping',  verifier_name: 'verify_boxes_shipping.py',   status: 'WARN',    last_run_at: '2026-05-15 05:08 PDT',   message: 'Ecoroses QBV, Flodecol FB, Megaflor EB/EB-M/SB-M unverified (no FedEx labels)' },
  { layer: '4 -- Target Price',      verifier_name: 'verify_target_price.py',     status: 'MISSING', last_run_at: '',                       message: 'target_price_v2 not materialized daily across vendors. MF-only today.' },
  { layer: '5 -- K2K Mirror',        verifier_name: 'verify_k2k_mirror.py',       status: 'FAIL',    last_run_at: '2026-05-15 05:11 PDT',   message: 'eshop scraper failed 2026-05-13 -- 179 SKUs stale. Ghost auth expired today.' },
  { layer: '6 -- Floropolis <-> K2K',verifier_name: 'verify_floropolis_k2k.py',   status: 'FAIL',    last_run_at: '2026-05-15 05:12 PDT',   message: '0% mapped. 1000 products on floropolis.com, 0 in_eshop=true.' },
  { layer: '7 -- Reconciliation',    verifier_name: 'verify_supply_health.py',    status: 'MISSING', last_run_at: '',                       message: 'Cross-layer health verifier not built yet.' },
  { layer: '8 -- Override Layer',    verifier_name: 'verify_admin_consistency.py', status: 'MISSING', last_run_at: '',                      message: 'New layer -- verifier owed by Job_PM. Proves UI == sources x overrides.' },
];

// ============================================================================
// SPECIALIZATION PROPOSALS (Tab a of /admin-catalog-proposals)
// ============================================================================

export const SPECIALIZATION_PROPOSALS: SpecializationProposal[] = [
  // ============= CUTOVER BLOCKERS (full specs) =============
  {
    id: 'B5',
    area: 'backend',
    title: 'API Contract Steward',
    priority: 'cutover_blocker',
    why: 'Komet + FedEx + Stripe + Supabase contracts can drift silently. When they do, our pipeline breaks and the customer notices first. Critical before checkout cutover.',
    scope: [
      'Maintain versioned JSON schemas for every external API we consume',
      'Run contract tests daily against each provider (Komet, FedEx, Stripe, Supabase RPC)',
      'Alert on breaking changes within 1h, write migration spec within 24h',
      'Maintain a contracts/ folder with TS types auto-generated from schemas',
      'Coordinate version bumps with Rose (Komet), JJ (FedEx), Nahua (Stripe)',
    ],
    raci: { r: 'New: API Contract Steward agent (or Nahua extension)', a: 'Facu', c: 'Rose, JJ, Job', i: 'All agents' },
    inbound_contracts: ['Provider OpenAPI / JSON schema (Komet, FedEx, Stripe)', 'Live API responses (sampled)'],
    outbound_contracts: ['contracts/*.json (versioned)', 'contracts_status.md (PASS/FAIL per provider)', 'breaking_change_alerts.md'],
    cost_estimate: '~6-8h setup + ~2h/wk ongoing. Tools: Pact or Spectral (free).',
    detail_specced: true,
    status: 'awaiting_facu',
  },
  {
    id: 'I1',
    area: 'infra',
    title: 'Observability (metrics, logs, traces, SLOs, alerts)',
    priority: 'cutover_blocker',
    why: 'Post-cutover, when checkout breaks the customer notices first. Unacceptable. Need SLOs per critical path + alerts that page before customer impact.',
    scope: [
      'Define SLOs per critical path (checkout, dispatch, admin save, daily report send)',
      'Wire structured logs (Pino) + traces (OpenTelemetry) into Supabase + Vercel + GitHub Actions jobs',
      'Dashboards in Grafana Cloud (free tier) or Better Stack',
      'Alerts to faculavino@gmail.com + Slack via webhook',
      'Weekly SLO scorecard (consistency_check.py extension)',
    ],
    raci: { r: 'New: SRE / Observability agent (or Nahua extension)', a: 'Facu', c: 'Rose, Job', i: 'All agents' },
    inbound_contracts: ['App logs (Pino structured)', 'Trace IDs from Vercel/Supabase', 'GitHub Actions run logs'],
    outbound_contracts: ['SLO dashboard URLs', 'alerts_config.yaml', 'weekly_slo_scorecard.md'],
    cost_estimate: 'Grafana Cloud free tier (10k series). ~12h setup + ~3h/wk ongoing.',
    detail_specced: true,
    status: 'awaiting_facu',
  },
  {
    id: 'I2',
    area: 'infra',
    title: 'Security Engineer (TOTP, RLS, secrets, PCI compliance)',
    priority: 'cutover_blocker',
    why: 'Stripe brings PCI scope. RLS policies, secret rotation, TOTP enforcement, device approval flow -- all need formalization before live charges.',
    scope: [
      'RLS policy review across all Supabase tables (orders, payments, invoices, addresses, users)',
      'Secret rotation discipline (Stripe keys, Komet token, FedEx REL_NUMBER, Supabase service key)',
      'TOTP enforcement audit on admin routes',
      'Device approval audit log review (Facu approves JJ, never reverse)',
      'PCI compliance documentation for Stripe SetupIntent flow',
      'Annual pen-test scoping',
    ],
    raci: { r: 'New: Security agent (or formalize Nahua subset)', a: 'Facu', c: 'Job (admin UI), Rose (DB)', i: 'All' },
    inbound_contracts: ['RLS policies', 'Auth flow diagrams', 'Secret inventory'],
    outbound_contracts: ['security_audit_log.md (monthly)', 'rotated_secrets.md (rotation log)', 'pci_compliance_status.md'],
    cost_estimate: '~10h initial audit + ~4h/mo ongoing. Pen-test annual: $3-5k external.',
    detail_specced: true,
    status: 'awaiting_facu',
  },
  {
    id: 'B1',
    area: 'backend',
    title: 'Pricing Engine owner (multi-country target_price_v2)',
    priority: 'cutover_blocker',
    why: 'Pricing today lives as scripts. Multi-country shipping configs + override layer + GPM bands need a proper engine that materializes target_price_v2 daily and recomputes on config edit.',
    scope: [
      'Daily materialization of target_price_v2 across all vendors x quality_families x delivery_weeks',
      'Recompute trigger on box_dim / shipping_config / GPM target edit (event-driven, not just daily)',
      'Multi-country shipping_config table lookup per vendor',
      'Override layer overlay (price_overrides, discount_rules)',
      'GPM band classification (green / yellow / red) with configurable thresholds',
      'Breakdown JSON for transparency in admin UI',
    ],
    raci: { r: 'Rose (extends current pricing scripts) -- new agent if Rose load too high', a: 'Facu', c: 'Job (consumer), Alvar (cost data)', i: 'All' },
    inbound_contracts: ['vendor_sku_cost', 'vendor_boxes', 'shipping_config', 'gpm_targets'],
    outbound_contracts: ['target_price_v2 (materialized table)', 'verify_target_price.py (paired verifier)'],
    cost_estimate: '~16h initial build + ~2h/wk ongoing. Runs as Supabase pg_cron or GitHub Actions.',
    detail_specced: true,
    status: 'awaiting_facu',
  },
  {
    id: 'F2',
    area: 'frontend',
    title: 'Frontend QA pipeline (visual regression + a11y + perf)',
    priority: 'cutover_blocker',
    why: 'Today: I test manually. As admin UI grows to 17+ routes (existing 9 + this catalog 8), regression risk is high. Admin breaks = ops breaks = revenue stops.',
    scope: [
      'Visual regression: Percy or Chromatic (free for small teams)',
      'a11y scanning: axe-core in CI (GitHub Actions)',
      'Performance budgets: Lighthouse CI with thresholds (p95 < 800ms, CLS < 0.1)',
      'Cross-browser: Chrome + Safari (Firefox optional)',
      'PR blocking on regression > threshold',
    ],
    raci: { r: 'Job (with Nahua infra)', a: 'Facu', c: 'Cande (visual taste)', i: 'All' },
    inbound_contracts: ['UI changes via PR', 'Baseline screenshots'],
    outbound_contracts: ['PR comments with visual diffs', 'qa_failures_log.md'],
    cost_estimate: 'Percy free <5k snapshots/mo. Chromatic similar. ~8h setup + ~1h/wk maintenance.',
    detail_specced: true,
    status: 'awaiting_facu',
  },
  {
    id: 'F3',
    area: 'frontend',
    title: 'UX writer / microcopy owner',
    priority: 'cutover_blocker',
    why: 'Approval queue warnings are critical -- bad copy = Facu approves without reading. Empty states, error states, confirmation modals all need consistent voice.',
    scope: [
      'Microcopy catalog (empty states, errors, confirmations, warnings)',
      'Approval warning templates with severity levels',
      'Brand voice enforcement in product copy (extends Cande_Content/brand_voice.md)',
      'Tooltip + onboarding copy for admin screens',
      'Localization-ready strings (future Spanish for vendor portal)',
    ],
    raci: { r: 'Cande_Content (extends brand voice scope)', a: 'Facu', c: 'Job (consumer of copy), Talin (marketing voice consistency)', i: 'All' },
    inbound_contracts: ['Brand voice canonical (brand_voice.md)', 'UI mockup states to copy'],
    outbound_contracts: ['microcopy_catalog.md', 'approval_warning_templates.md'],
    cost_estimate: '~6h initial catalog + ~1-2h/wk as new screens ship. Extension of Cande role.',
    detail_specced: true,
    status: 'awaiting_facu',
  },
  // ============= PHASE 2 (summary only) =============
  {
    id: 'B3',
    area: 'backend',
    title: 'Vendor Ingestion Adapter framework',
    priority: 'phase_2',
    why: 'Vendors send shitty emails, WhatsApp voice notes, photos of handwritten lists. Today: manual parsing. Without this, doesnt scale past 5 vendors.',
    scope: ['Parser plugins per vendor (email PDF, WhatsApp voice, CSV)', 'Claude-powered fallback for unknown formats', 'Outputs normalized vendor_ingest_staging table'],
    raci: { r: 'New agent', a: 'Facu', c: 'Job (UI consumer), Rose (DB)', i: 'All' },
    inbound_contracts: ['Raw vendor inputs (email, WhatsApp, CSV, image)'],
    outbound_contracts: ['vendor_ingest_staging table'],
    cost_estimate: '~24h initial framework + 4-8h per new vendor format',
    detail_specced: false,
    status: 'awaiting_facu',
  },
  {
    id: 'B4',
    area: 'backend',
    title: 'SKU Mapper (LLM-assisted name -> quality_family_id)',
    priority: 'phase_2',
    why: 'Different vendors call the same flower different things. Without canonical mapping, duplicate SKUs explode and the catalog becomes unusable.',
    scope: ['Vendor name + attributes -> parent SKU + quality_family_id with confidence', '< 0.85 confidence -> human review queue', 'Training data curation from accepted mappings'],
    raci: { r: 'New agent or Rose extension', a: 'Facu', c: 'Job (review UI)', i: 'All' },
    inbound_contracts: ['vendor_ingest_staging rows'],
    outbound_contracts: ['sku_mappings table with confidence', 'mapping review queue'],
    cost_estimate: '~16h initial + Claude API per mapping (~$0.001/match)',
    detail_specced: false,
    status: 'awaiting_facu',
  },
  {
    id: 'B2',
    area: 'backend',
    title: 'Decision Engine (which vendor offer to display)',
    priority: 'phase_2',
    why: 'When 4 vendors have Rose Mondial 60cm, the website cant show all 4. Need logic to pick the best offer or aggregate.',
    scope: ['Inputs: price, available stems, quality score, vendor reliability', 'Tuning loop based on conversion + customer feedback', 'Outputs display_offer view consumed by floropolis.com'],
    raci: { r: 'Job + Rose joint', a: 'Facu', c: 'Talin (marketing input)', i: 'All' },
    inbound_contracts: ['unified_inventory', 'target_price_v2', 'vendor_reliability_scores'],
    outbound_contracts: ['display_offer view'],
    cost_estimate: '~20h initial logic + tuning ongoing',
    detail_specced: false,
    status: 'awaiting_facu',
  },
  {
    id: 'F1',
    area: 'frontend',
    title: 'Design System owner (tokens, components, motion, a11y)',
    priority: 'phase_2',
    why: 'Tailwind + ad-hoc components today. At 17+ admin routes drift is guaranteed. Need canonical tokens + component library + motion language.',
    scope: ['Design tokens (already: Emerald-600, Plus Jakarta, ASCII rule)', 'Component library (Button, Table, Modal, Badge, Tabs)', 'Motion specs', 'a11y baseline'],
    raci: { r: 'Cande_Content extension or new', a: 'Facu', c: 'Job', i: 'All' },
    inbound_contracts: ['Brand voice + design canonical files'],
    outbound_contracts: ['design_tokens.ts', 'components/ library'],
    cost_estimate: '~24h initial + ~2h/wk maintenance',
    detail_specced: false,
    status: 'awaiting_facu',
  },
  {
    id: 'F4',
    area: 'frontend',
    title: 'Data viz specialist',
    priority: 'phase_2',
    why: 'Decision Engine previews, GPM bands, cascade impact charts need real visualization, not just tables.',
    scope: ['Chart library selection (Recharts or Tremor)', 'GPM band visualization', 'Cascade impact preview charts', 'Sell-through trends for vendor portal'],
    raci: { r: 'Job (with Rose data)', a: 'Facu', c: 'Talin', i: 'All' },
    inbound_contracts: ['Aggregated metrics from Rose'],
    outbound_contracts: ['Chart components'],
    cost_estimate: '~12h initial + per-chart as needed',
    detail_specced: false,
    status: 'awaiting_facu',
  },
  // ============= PHASE 3 (summary only) =============
  {
    id: 'B6',
    area: 'backend',
    title: 'Search / Discovery engineer',
    priority: 'phase_3',
    why: 'At 5000+ SKUs across many vendors, search becomes a product. Faceted, ranked, autocomplete.',
    scope: ['Faceted search (vendor, country, category, delivery week)', 'Autocomplete on quality_family', 'Ranking algorithm tuned by conversion'],
    raci: { r: 'New', a: 'Facu', c: 'Job, Talin', i: 'All' },
    inbound_contracts: ['unified_inventory view'],
    outbound_contracts: ['Search API endpoint'],
    cost_estimate: '~24h + infra (Algolia or Meilisearch ~$30/mo)',
    detail_specced: false,
    status: 'awaiting_facu',
  },
  {
    id: 'I3',
    area: 'infra',
    title: 'Data Pipeline Engineer',
    priority: 'phase_3',
    why: 'As pipelines multiply (ingestion adapters, decision engine, materialized views, override layer, audit), reliability slips without dedicated ownership.',
    scope: ['Pipeline orchestration (dbt or similar)', 'Backfill + replay tooling', 'Lineage tracking'],
    raci: { r: 'New or Rose extension', a: 'Facu', c: 'All data producers', i: 'All' },
    inbound_contracts: ['Pipeline DAGs'],
    outbound_contracts: ['pipeline_health.md', 'replay_log.md'],
    cost_estimate: '~32h initial + ongoing',
    detail_specced: false,
    status: 'awaiting_facu',
  },
  {
    id: 'I4',
    area: 'infra',
    title: 'FinOps cost watcher',
    priority: 'phase_3',
    why: 'Vercel + Supabase + Komet + FedEx + Stripe + Claude API. Nobody owns spend per layer today. Surprise bills inevitable.',
    scope: ['Monthly spend report per layer', 'Threshold alerts', 'Cost per critical action (per order, per quote, per session)'],
    raci: { r: 'New (light role)', a: 'Facu', c: 'Nahua, Rose', i: 'All' },
    inbound_contracts: ['Provider invoices (auto-parsed)'],
    outbound_contracts: ['monthly_finops.md'],
    cost_estimate: '~4h setup + ~2h/mo',
    detail_specced: false,
    status: 'awaiting_facu',
  },
  {
    id: 'I5',
    area: 'infra',
    title: 'Release Engineer (flags, canary, rollback)',
    priority: 'phase_3',
    why: 'pre-deploy-check.sh only today. Every deploy is all-or-nothing. Need feature flags + canary + tested rollback.',
    scope: ['Feature flag system (GrowthBook or self-hosted)', 'Canary release pattern via Vercel preview deploys + traffic split', 'Rollback playbook + drill'],
    raci: { r: 'Job extension or new', a: 'Facu', c: 'Nahua', i: 'All' },
    inbound_contracts: ['Deploy events'],
    outbound_contracts: ['flags_state.json', 'rollback_playbook.md'],
    cost_estimate: '~12h initial + GrowthBook free or self-host',
    detail_specced: false,
    status: 'awaiting_facu',
  },
];

// ============================================================================
// SPECS ALREADY PROPOSED (Tab b of /admin-catalog-proposals)
// ============================================================================

export type AlreadyProposed = {
  id: string;
  title: string;
  category: 'agent' | 'contract' | 'flow' | 'table' | 'verifier';
  summary: string;
  status: 'proposed' | 'accepted' | 'in_progress';
};

export const ALREADY_PROPOSED: AlreadyProposed[] = [
  { id: 'ap_001', title: 'Vendor Ingestion Adapter (agent)',            category: 'agent',    summary: 'Parses email/WhatsApp/CSV/image inputs into normalized vendor_ingest_staging table',           status: 'proposed' },
  { id: 'ap_002', title: 'SKU Mapper (agent)',                          category: 'agent',    summary: 'Maps vendor name + attributes -> parent SKU + quality_family_id with confidence score',     status: 'proposed' },
  { id: 'ap_003', title: 'Decision Engine (function)',                  category: 'agent',    summary: 'Picks which vendor offer to display per quality_family x delivery_week. Tuning loop.',    status: 'proposed' },
  { id: 'ap_004', title: 'Vendor Comms Agent (P2)',                     category: 'agent',    summary: 'Routes vendor inbox: cost dispute -> Rose, new SKU pitch -> Facu+Job. NOT Alvar, NOT Enzo.', status: 'proposed' },
  { id: 'ap_005', title: 'Override approval flow',                      category: 'flow',     summary: 'admin_proposals -> warnings shown -> admin_approvals (Facu signs) -> override layer applied', status: 'proposed' },
  { id: 'ap_006', title: 'unified_inventory view',                      category: 'contract', summary: 'Joins K2K live + T2 + T3 + staged email/WhatsApp into single inventory surface',           status: 'proposed' },
  { id: 'ap_007', title: 'target_price_v2 materialized table',          category: 'contract', summary: 'cost + box_share + shipping + margin breakdown JSON per SKU per vendor per delivery_week',  status: 'proposed' },
  { id: 'ap_008', title: 'admin_proposals / admin_approvals tables',    category: 'table',    summary: 'Every edit proposed by anyone, approved by Facu. Audit trail per change.',                status: 'proposed' },
  { id: 'ap_009', title: 'discount_rules table',                        category: 'table',    summary: 'Scoped by category/vendor/SKU/client with expiry + warnings + approval audit',             status: 'proposed' },
  { id: 'ap_010', title: 'visibility_rules table',                      category: 'table',    summary: 'Clear rules per source/quality_family/vendor. Maintained by Job, reviewed quarterly by Facu.', status: 'proposed' },
  { id: 'ap_011', title: 'shipping_config table (multi-country/port)',  category: 'table',    summary: 'Per-{country, port} rates, fuel mults, dim divisors, REL_NUMBERs, customs fees',          status: 'proposed' },
  { id: 'ap_012', title: 'override_audit (immutable)',                  category: 'table',    summary: 'Every approved override recorded immutably with reason + approver + timestamp',           status: 'proposed' },
  { id: 'ap_013', title: '9 verifiers (Pipeline Law)',                  category: 'verifier', summary: 'One verifier per layer. Today: 3 exist (T1, ghost, price_drift). Need 6 more.',           status: 'proposed' },
  { id: 'ap_014', title: 'verify_admin_consistency.py',                 category: 'verifier', summary: 'Job-owned. Proves UI shows = target_price_v2 x discount_rules x visibility_rules. Blocks send on FAIL.', status: 'proposed' },
];
