/**
 * Promo codes — managed here, NOT in floropolis_products.ts.
 * floropolis_products.ts is auto-generated by generate-products.mjs and gets
 * overwritten on every catalog regen. Keeping promo codes here prevents them
 * from being silently wiped (L-19, 2026-03-30).
 *
 * To add a code: add an entry below and redeploy.
 * To expire a code: set active: false OR set expiry to a past date.
 */

export const PROMO_CODES = {
  MAGIC10: {
    discount_type: "percentage" as const,
    discount_value: 10,
    scope: "all" as const,
    scope_filter: "",
    expiry: "2026-06-30",
    active: true,
  },
  SPRING15: {
    discount_type: "percentage" as const,
    discount_value: 15,
    scope: "category" as const,
    scope_filter: "Ranunculus,Anemone,Delphinium",
    expiry: "2026-04-30",
    active: true,
  },
  WELCOME10: {
    discount_type: "percentage" as const,
    discount_value: 10,
    scope: "all" as const,
    scope_filter: "",
    expiry: "2026-12-31",
    active: true,
    first_order_only: true,
  },
  COMEBACK10: {
    discount_type: "percentage" as const,
    discount_value: 10,
    scope: "all" as const,
    scope_filter: "",
    expiry: "2026-12-31",
    active: true,
  },
  MDY10: {
    discount_type: "percentage" as const,
    discount_value: 10,
    scope: "all" as const,
    scope_filter: "",
    expiry: "2026-04-17",
    active: true,
  },
} as const;
