/**
 * Rose catalog for /shop/roses: 30+ varieties organized by value tier.
 */

export type RoseTier = "value" | "popular" | "premium" | "assorted";

export interface RoseVariety {
  id: string;
  name: string;
  color: string;
  pricePerStem: number;
  stemsPerBunch: number;
  stemLength: string;
  /** e.g. "40, 50, 60, 70cm" or "40–70cm" */
  availableLengths: string;
  /** e.g. "$1.30–$1.55" or "From $1.30" */
  priceRange: string;
  image: string;
  tier: RoseTier;
  badge?: string;
}

function rose(
  p: Omit<RoseVariety, "id"> & { id?: string }
): RoseVariety {
  const id =
    p.id ??
    p.name
      .toLowerCase()
      .replace(/\s+/g, "-")
      .replace(/[^a-z0-9-]/g, "");
  return { ...p, id };
}

const IMG = {
  red: "/images/shop/Freedom.png",
  white: "/images/shop/white-tibet-ai.png",
  orange: "/images/shop/orange-crush-ai.png",
  pink: "/images/shop/Pink_Floyd.png",
  lavender: "/images/shop/lavender-deep-purple-ai.png",
};

export const ROSE_VARIETIES: RoseVariety[] = [
  // ——— BEST VALUE (under $1.30/stem) ———
  rose({
    name: "White Tibet",
    color: "White",
    pricePerStem: 1.28,
    stemsPerBunch: 25,
    stemLength: "40-70cm",
    availableLengths: "40, 50, 60, 70cm",
    priceRange: "$1.28–$1.55",
    image: IMG.white,
    tier: "value",
    badge: "Best price",
  }),
  rose({
    name: "Mondial",
    color: "White",
    pricePerStem: 1.25,
    stemsPerBunch: 25,
    stemLength: "40-50cm",
    availableLengths: "40, 50cm",
    priceRange: "From $1.25",
    image: IMG.white,
    tier: "value",
  }),
  rose({
    name: "Vendela",
    color: "Cream",
    pricePerStem: 1.26,
    stemsPerBunch: 25,
    stemLength: "40-50cm",
    availableLengths: "40, 50cm",
    priceRange: "From $1.26",
    image: IMG.white,
    tier: "value",
  }),
  rose({
    name: "Avalanche",
    color: "White",
    pricePerStem: 1.28,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.28–$1.38",
    image: IMG.white,
    tier: "value",
  }),
  rose({
    name: "Tineke",
    color: "Cream / Ivory",
    pricePerStem: 1.27,
    stemsPerBunch: 25,
    stemLength: "40-50cm",
    availableLengths: "40, 50cm",
    priceRange: "From $1.27",
    image: IMG.white,
    tier: "value",
  }),
  rose({
    name: "Explorer",
    color: "Red",
    pricePerStem: 1.29,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.29–$1.42",
    image: IMG.red,
    tier: "value",
  }),
  rose({
    name: "Sweet Akito",
    color: "White",
    pricePerStem: 1.26,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.26–$1.44",
    image: IMG.white,
    tier: "value",
  }),
  rose({
    name: "Mimi",
    color: "Pink",
    pricePerStem: 1.28,
    stemsPerBunch: 25,
    stemLength: "40-50cm",
    availableLengths: "40, 50cm",
    priceRange: "From $1.28",
    image: IMG.pink,
    tier: "value",
  }),
  // ——— POPULAR (Tibet, Orange Crush, Free Spirit, Cool Water + favorites) ———
  rose({
    name: "Orange Crush",
    color: "Orange",
    pricePerStem: 1.45,
    stemsPerBunch: 25,
    stemLength: "50-70cm",
    availableLengths: "50, 60, 70cm",
    priceRange: "$1.45–$1.62",
    image: IMG.orange,
    tier: "popular",
  }),
  rose({
    name: "Free Spirit",
    color: "Bicolor Pink & Yellow",
    pricePerStem: 1.58,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.58–$1.65",
    image: IMG.pink,
    tier: "popular",
  }),
  rose({
    name: "Cool Water",
    color: "Lavender",
    pricePerStem: 1.55,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.55–$1.95",
    image: IMG.lavender,
    tier: "popular",
  }),
  rose({
    name: "Pink Faith",
    color: "Pink",
    pricePerStem: 1.52,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.52–$1.58",
    image: IMG.pink,
    tier: "popular",
    badge: "Bestseller",
  }),
  rose({
    name: "Misty Blue",
    color: "Lavender",
    pricePerStem: 1.58,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.58–$1.65",
    image: IMG.lavender,
    tier: "popular",
  }),
  rose({
    name: "Vienna",
    color: "White",
    pricePerStem: 1.52,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.52–$1.58",
    image: IMG.white,
    tier: "popular",
  }),
  rose({
    name: "Coral",
    color: "Coral",
    pricePerStem: 1.62,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.62–$1.68",
    image: IMG.orange,
    tier: "popular",
  }),
  rose({
    name: "Hot Pink",
    color: "Hot Pink",
    pricePerStem: 1.6,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.60–$1.65",
    image: IMG.pink,
    tier: "popular",
  }),
  rose({
    name: "Sierra",
    color: "Red",
    pricePerStem: 1.58,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.58–$1.65",
    image: IMG.red,
    tier: "popular",
  }),
  rose({
    name: "Luna",
    color: "Ivory",
    pricePerStem: 1.55,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.55–$1.62",
    image: IMG.white,
    tier: "popular",
  }),
  rose({
    name: "Lavender Deep Purple",
    color: "Lavender",
    pricePerStem: 1.48,
    stemsPerBunch: 25,
    stemLength: "50cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.45–$1.52",
    image: IMG.lavender,
    tier: "popular",
  }),
  rose({
    name: "Espresso",
    color: "Brown / Terracotta",
    pricePerStem: 1.65,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.65–$1.72",
    image: IMG.orange,
    tier: "popular",
  }),
  rose({
    name: "Peach Avalanche",
    color: "Peach",
    pricePerStem: 1.68,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.68–$1.75",
    image: IMG.orange,
    tier: "popular",
  }),
  // ——— PREMIUM (Quicksand, Moonstone, Barista, Playa Blanca + designer) ———
  rose({
    name: "Quicksand",
    color: "Blush",
    pricePerStem: 1.82,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.82–$1.92",
    image: IMG.pink,
    tier: "premium",
  }),
  rose({
    name: "Moonstone",
    color: "Blush / Mauve",
    pricePerStem: 1.95,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.95–$2.05",
    image: IMG.pink,
    tier: "premium",
  }),
  rose({
    name: "Barista",
    color: "Brown / Terracotta",
    pricePerStem: 1.88,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.88–$1.98",
    image: IMG.orange,
    tier: "premium",
  }),
  rose({
    name: "Playa Blanca",
    color: "White",
    pricePerStem: 1.85,
    stemsPerBunch: 25,
    stemLength: "60-70cm",
    availableLengths: "60, 70cm",
    priceRange: "$1.85–$1.98",
    image: IMG.white,
    tier: "premium",
  }),
  rose({
    id: "freedom-red-rose",
    name: "Freedom Red Rose",
    color: "Red",
    pricePerStem: 1.88,
    stemsPerBunch: 25,
    stemLength: "60cm",
    availableLengths: "40, 50, 60, 70cm",
    priceRange: "$1.52–$2.05",
    image: IMG.red,
    tier: "premium",
    badge: "Bestseller",
  }),
  rose({
    name: "Freedom Deep Red",
    color: "Deep Red",
    pricePerStem: 1.92,
    stemsPerBunch: 25,
    stemLength: "60-70cm",
    availableLengths: "60, 70cm",
    priceRange: "$1.92–$2.05",
    image: IMG.red,
    tier: "premium",
  }),
  rose({
    name: "Grand Gala",
    color: "Red",
    pricePerStem: 1.95,
    stemsPerBunch: 25,
    stemLength: "60-70cm",
    availableLengths: "60, 70cm",
    priceRange: "$1.95–$2.08",
    image: IMG.red,
    tier: "premium",
  }),
  rose({
    name: "Madame Delbard",
    color: "Pink",
    pricePerStem: 1.82,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.82–$1.92",
    image: IMG.pink,
    tier: "premium",
  }),
  rose({
    name: "Sweet Promise",
    color: "Blush Pink",
    pricePerStem: 1.88,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.88–$1.98",
    image: IMG.pink,
    tier: "premium",
  }),
  rose({
    name: "Rebecca",
    color: "Bicolor Pink",
    pricePerStem: 1.92,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.92–$2.02",
    image: IMG.pink,
    tier: "premium",
  }),
  rose({
    name: "Ocean Song",
    color: "Lavender / Mauve",
    pricePerStem: 1.98,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.98–$2.08",
    image: IMG.lavender,
    tier: "premium",
  }),
  rose({
    name: "White Naomi",
    color: "White",
    pricePerStem: 1.78,
    stemsPerBunch: 25,
    stemLength: "60-70cm",
    availableLengths: "60, 70cm",
    priceRange: "$1.78–$1.92",
    image: IMG.white,
    tier: "premium",
  }),
  rose({
    name: "Avalanche+ 70",
    color: "White",
    pricePerStem: 1.88,
    stemsPerBunch: 25,
    stemLength: "70cm",
    availableLengths: "70cm",
    priceRange: "From $1.88",
    image: IMG.white,
    tier: "premium",
  }),
  rose({
    name: "Voodoo",
    color: "Orange / Red Bicolor",
    pricePerStem: 1.95,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$1.95–$2.05",
    image: IMG.orange,
    tier: "premium",
  }),
  rose({
    name: "Black Baccara",
    color: "Dark Red / Black",
    pricePerStem: 2.08,
    stemsPerBunch: 25,
    stemLength: "50-60cm",
    availableLengths: "50, 60cm",
    priceRange: "$2.08–$2.18",
    image: IMG.red,
    tier: "premium",
  }),
  rose({
    name: "Rosalinda",
    color: "Red",
    pricePerStem: 1.98,
    stemsPerBunch: 25,
    stemLength: "60-70cm",
    availableLengths: "60, 70cm",
    priceRange: "$1.98–$2.08",
    image: IMG.red,
    tier: "premium",
  }),
  // ——— ASSORTED BUNDLES (linked to live PDPs) ———
  rose({
    id: "assorted-rainbow",
    name: "Assorted Rainbow",
    color: "All colors",
    pricePerStem: 1.40,
    stemsPerBunch: 25,
    stemLength: "50cm",
    availableLengths: "50cm",
    priceRange: "From $1.40/stem",
    image: "/images/shop/combos/roses-assorted-rainbow_3f985d44682c.png",
    tier: "assorted",
    badge: "Most popular",
  }),
  rose({
    id: "assorted-red",
    name: "Assorted Red",
    color: "Red tones",
    pricePerStem: 1.47,
    stemsPerBunch: 25,
    stemLength: "50cm",
    availableLengths: "50cm",
    priceRange: "From $1.47/stem",
    image: "/images/shop/combos/roses-assorted-reds_28e50b75acfe.png",
    tier: "assorted",
  }),
  rose({
    id: "assorted-pink",
    name: "Assorted Pink",
    color: "Pink tones",
    pricePerStem: 1.47,
    stemsPerBunch: 25,
    stemLength: "50cm",
    availableLengths: "50cm",
    priceRange: "From $1.47/stem",
    image: "/images/shop/combos/roses-assorted-pinks_e4640517921b.png",
    tier: "assorted",
  }),
  rose({
    id: "assorted-white",
    name: "Assorted White",
    color: "White tones",
    pricePerStem: 1.47,
    stemsPerBunch: 25,
    stemLength: "50cm",
    availableLengths: "50cm",
    priceRange: "From $1.47/stem",
    image: "/images/shop/combos/roses-assorted-whites_edb0ab505fd1.png",
    tier: "assorted",
  }),
  rose({
    id: "assorted-cream",
    name: "Assorted Cream",
    color: "Cream tones",
    pricePerStem: 1.47,
    stemsPerBunch: 25,
    stemLength: "50cm",
    availableLengths: "50cm",
    priceRange: "From $1.47/stem",
    image: "/images/shop/combos/roses-assorted-creams_a9067a47cbe2.png",
    tier: "assorted",
  }),
];

/** Group roses by tier for the page sections */
export function getRosesByTier(): Record<RoseTier, RoseVariety[]> {
  return {
    value: ROSE_VARIETIES.filter((r) => r.tier === "value"),
    popular: ROSE_VARIETIES.filter((r) => r.tier === "popular"),
    premium: ROSE_VARIETIES.filter((r) => r.tier === "premium"),
    assorted: ROSE_VARIETIES.filter((r) => r.tier === "assorted"),
  };
}

export const ROSES_SHOP_URL = "/shop?category=Rose";
