// Shared published-catalog resolver for the buy path.
// v1 | 2026-06-15 | Job_PM — buy_path_identity_and_price_coherence
//
// THE single price + identity source for checkout. Both checkout entry points
// (app/api/checkout/sku-details/route.ts and app/api/checkout/session/route.ts)
// resolve cart items through getPublishedSkuMap() so that the price the
// storefront SHOWS is exactly the price checkout CHARGES — shown == charged by
// construction, because both surfaces read the identical `price` field off the
// identical module (lib/data/products.ts).
//
// Why this file exists (the break it fixes):
//   - Old: storefront cart carried Product.id (an FNV hash of the uuid, range
//     0..2e9) and checkout resolved it as floropolis_inventory_mirror.id (real
//     range 6676-7881). The hash never landed in that range -> sku_missing -> a
//     shopper coming from /shop could NOT check out. AND the charge price came
//     from the live mirror while the shown price came from this static catalog
//     => shown != charged.
//   - New: cart identity is the real catalog_published SKU uuid (Product.sku_id,
//     a string). Checkout resolves that uuid against this same static catalog by
//     sku_id. One source, one gate.
//
// The GATE is free: lib/data/products.ts is generated from catalog_published
// (the 16-gate publish authority, 798 rows). A uuid absent from this map is
// unresolvable -> sku-details returns it in missing_ids and session/route.ts
// throws TotalsError('sku_missing') -> 400. Unpublished/blocked SKUs are
// rejected at checkout with no extra code and no live re-query.
//
// Staleness note: this is a build-time artifact (regenerated by
// scripts/generate-products.mjs + redeploy). Coherence holds for what is
// deployed; a farm_cost change isn't live until regenerate. Acceptable for MVP
// (shown and charged share one artifact, so they cannot disagree). A durable
// canonical_price table is the later follow-up, out of scope here.
//
// Plain server-importable data — lib/data/products.ts has no "use client" and
// no runtime-only imports, so both route handlers can import this safely.

import { products as publishedProducts } from "@/lib/data/products";

/** Normalized catalog row used by the checkout resolver. Mirrors exactly the
 *  fields the buy path needs: identity (uuid + legacy int id), display snapshot
 *  fields, and the locked price. Prices/deals come straight off lib/data/
 *  products.ts so they equal what the storefront renders. */
export interface CatalogSku {
  /** Real catalog_published SKU uuid — the cart identity. */
  sku_uuid: string;
  /** Legacy FNV-hashed int id (Product.id). Kept ONLY for the order_lines.sku_id
   *  bigint NOT NULL column; never used as cart identity. */
  legacy_id: number;
  name: string;
  variety: string | null;
  length: string | null;
  unit: string | null;
  vendor: string | null;
  category: string | null;
  price: number;
  is_on_deal: boolean;
  deal_price: number | null;
  images: unknown | null;
  stems_per_bunch: number | null;
  units_per_box: number | null;
}

let _cache: Map<string, CatalogSku> | null = null;

/**
 * Build (and memoize) the uuid -> CatalogSku map over the published static
 * catalog. Keyed by the uuid Product.sku_id. Module-level + immutable for the
 * process lifetime (the catalog only changes at build time), so we build once.
 */
export function getPublishedSkuMap(): Map<string, CatalogSku> {
  if (_cache) return _cache;
  const map = new Map<string, CatalogSku>();
  for (const p of publishedProducts) {
    const uuid = String(p.sku_id ?? "").trim();
    if (!uuid) continue; // defensive: every generated row has a uuid (798/798)
    map.set(uuid, {
      sku_uuid: uuid,
      legacy_id: Number(p.id),
      name: p.name,
      variety: p.variety ?? null,
      length: p.length ?? null,
      unit: p.unit ?? null,
      vendor: p.vendor ?? null,
      category: p.category ?? null,
      price: Number(p.price),
      is_on_deal: !!p.is_on_deal && p.deal_price != null,
      deal_price: p.deal_price != null ? Number(p.deal_price) : null,
      images: p.images ?? null,
      stems_per_bunch: p.stems_per_bunch != null ? Number(p.stems_per_bunch) : null,
      units_per_box: p.units_per_box != null ? Number(p.units_per_box) : null,
    });
  }
  _cache = map;
  return map;
}

/** Resolve a single uuid against the published catalog. Returns undefined if
 *  the SKU is not published (gate rejection). */
export function getPublishedSku(uuid: string): CatalogSku | undefined {
  return getPublishedSkuMap().get(String(uuid).trim());
}
